language: java
jdk: oraclejdk8
install: true
env:
  - IMAGE_NAME = anger-service/user-service
services:
  - docker
stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script: ./mvnw findbugs:findbugs
      script: ./mvnw checkstyle:checkstyle
      script:
        - ./mvnw clean install
        - bash <(curl -s https://codecov.io/bash)
        - docker-compose up --build -d
        - ./scripts/healthcheck.sh
        - docker-compose down
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t angerservice/user-service:$TRAVIS_BUILD_NUMBER .
        - docker push angerservice/user-service:$TRAVIS_BUILD_NUMBER
cache:
  directories:
  - $HOME/.m2

notifications:
    slack: microservices-course:kWyowfRrndmVbAVCZS41kaqM

