language: java
jdk: oraclejdk8
install: true
env:
  - IMAGE_NAME = anger-service/user-service
services:
  - docker
script:
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)
  - docker-compose up --build -d
  - ./scripts/healthcheck.sh $IMAGE_NAME
after_script:
  - docker-compose down
cache:
  directories:
  - $HOME/.m2
