version: '3'
services:
  user-service:
    build:
      context: .
    tty: true
    stdin_open: true
    environment:
      PORT: 8080
      ENVIRONMENT: 'dev'
      MONGO_URI: 'localhost'
    ports:
      - 8080:8080
    volumes:
      - ./config/:/var/app/user-service/config
    links:
      - mongo:mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:3.2.10
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.stats().ok' | mongo localhost:27017/test --quiet"]
      interval: 30s
      timeout: s
      retries: 3
