server:
  port: 8080

spring:
  application:
    name: user-service
    profiles:
        # The commented value for `active` can be replaced with valid Spring profiles to load.
        # Otherwise, it will be filled in by maven when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        # java -jar -Dspring.profiles.active=prod spring-boot-demo-0.0.1-SNAPSHOT.jar
  mvc:
    throw-exception-if-no-handler-found: false
  resources:
    add-mappings: true

logging:
  level:
    root: INFO
  file: ./logs/${spring.application.name}-server.log # Server logs
  accesslog:
    pattern: '%h %l %u [%t] "%r" %s %b "Referer: %i{Referer}" "X-Forwarded-For: %i{X-Forwarded-For}" "User-Agent: %i{User-Agent}"'
    file: ./logs/${spring.application.name}-access.log

management:
  security:
    enabled: true

security:
  basic:
    enabled: false
  user:
    name: admin
    password: password

---

spring:
    profiles:
        active: dev
        include: swagger

management:
  security:
    enabled: true

security:
  basic:
    enabled: false
  user:
    name: admin
    password: password

---

spring:
    profiles: prod
    server:
        port: 8080
        compression:
            enabled: true
            mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
            min-response-size: 1024